### ISSUE TITLE
Pin to Bottom

### ISSUE THREAD

**Issue by rawkode** [barrymcgee/gatsby-plugin-scroll-indicator#131]
Is it possible to pin this to the bottom of the page, rather than the top?

**Comment by barrymcgee** [comment]
Hi @rawkode - due to uncertainties around infinite scrolling and flex layouts etc, it's difficult to add this functionality with confidence. I can always be sure of where a page will start but cannot always be sure where a page will end. 

However, if you figure out  a way to implement this reliably, I'll happily accept a PR.
